# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - new-feature
    - title: Enhancements 🛠
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - bug-fix
