name: EAS Build & Submit Staging

on:
  push:
    branches:
      - staging

jobs:
  eas-build-staging:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🧶 Install Project Dependencies
        run: yarn

      - name: 🍏 | 🤖 Build on EAS
        run: eas build --platform all --profile staging --non-interactive --auto-submit
        env:
          APP_VARIANT: staging
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          EXPO_PUBLIC_ANDROID_CLIENT_ID: ${{ vars.STAGING_EXPO_PUBLIC_ANDROID_CLIENT_ID }}
          EXPO_PUBLIC_IOS_CLIENT_ID: ${{ vars.STAGING_EXPO_PUBLIC_IOS_CLIENT_ID }}
          EXPO_PUBLIC_SENTRY_DSN: ${{ vars.STAGING_EXPO_PUBLIC_SENTRY_DSN }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.STAGING_EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          EXPO_PUBLIC_SUPABASE_URL: ${{ vars.STAGING_EXPO_PUBLIC_SUPABASE_URL }}
